name: Deploy to Cloud Run
on:
 push:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Set up Cloud SDK
       uses: google-github-actions/setup-gcloud@v0.2.1
       with:
         project_id: ${{ secrets.UWU_BOT_PROJECT_ID }}
         service_account_key: ${{ secrets.UWU_BOT }}
         export_default_credentials: true
     - name: Build and deploy to Cloud Run
       run: |
         docker build -t gcr.io/${{ secrets.UWU_BOT_PROJECT_ID }}/discord-bot .
         docker push gcr.io/${{ secrets.UWU_BOT_PROJECT_ID }}/discord-bot
         gcloud run deploy discord-bot --image gcr.io/${{ secrets.UWU_BOT_PROJECT_ID }}/discord-bot --update-env-vars DISCORD_BOT_TOKEN=TOKEN